server:
  port: 9393

spring:
  application:
    name: "appointment"
  #================================================================================================================================
  #                                                         MYSQL_PROPERTIES
  #================================================================================================================================
  datasource:
    url: jdbc:mysql://localhost:3309/appointmentsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: "http://localhost:8761/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "appointment"
    description: "appointment service microservice project for Spring Boot and Spring Cloud Microservices architecture with Eureka server"
    version: "0.0.1-SNAPSHOT"

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO

